
select CAT.CAT_ID,CAT.CAT_NAME,MIN(T3.MIN_PRICE) AS MIN_PRICE FROM CATEGORY CAT
JOIN
(SELECT P.CAT_ID,P.PRO_NAME,T2.* FROM PRODUCT P	
JOIN (SELECT PRO_ID,MIN(SUPP_PRICE) AS MIN_PRICE FROM SUPPLIER_PRICING GROUP  BY PRO_ID) AS T2
WHERE T2.PRO_ID=P.PRO_ID
) AS T3 WHERE T3.CAT_ID=CAT.CAT_ID
GROUP BY T3.CAT_ID